version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Installing Node.js modules
          command: |
            set -e
            npm install eslint@latest
            npm install eslint-plugin-html@latest
            npm install stylelint@latest
            npm install stylelint-config-standard@latest
            npm install postcss-html@latest
            npm install @stylelint/postcss-css-in-js@latest
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running ESLint
          command: |
            ./node_modules/.bin/eslint -v
            npm show eslint-plugin-html version
            ./node_modules/.bin/eslint ./
      - run:
          name: Running stylelint
          command: |
            ./node_modules/.bin/stylelint -v
            npm show stylelint-config-standard version
            npm show postcss-html version
            npm show @stylelint/postcss-css-in-js version
            ./node_modules/.bin/stylelint ./**/*.css ./**/*.html ./**/*.js
